<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\IcarusStarlink.Core\IcarusStarlink.Core.csproj" />
    <ProjectReference Include="..\IcarusStarlink.Diffing\IcarusStarlink.Diffing.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
