<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\IcarusStarlink.Core\IcarusStarlink.Core.csproj" />
    <ProjectReference Include="..\IcarusStarlink.Diffing\IcarusStarlink.Diffing.csproj" />
    <ProjectReference Include="..\IcarusStarlink.PakIO\IcarusStarlink.PakIO.csproj" />
    <ProjectReference Include="..\IcarusStarlink.Catalog\IcarusStarlink.Catalog.csproj" />
    <ProjectReference Include="..\IcarusStarlink.Storage\IcarusStarlink.Storage.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4129.50" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
