@echo off
setlocal enabledelayedexpansion
cd /d "%~dp0"

echo IcarusStarlink Uninstaller
echo.
echo This removes IcarusStarlink from this folder. Your Icarus game install
echo itself is never touched.
echo.
set /p KEEPDATA="Keep your mod library, profiles, settings, and other saved data? (Y/N): "

echo.
if /i "%KEEPDATA%"=="Y" (
    echo Keeping: Extracted_Mods, Library_Meta, Profiles, Cache, Pending_Downloads, Backups, WebView2, settings.json
    echo Removing: the app itself, plus Logs/Data/Staged_Build/Staged_UE4SS ^(all safely regenerated by the app^)
) else (
    echo Removing everything, including your mod library and saved data. This cannot be undone.
)
echo.
set /p CONFIRM="Type YES to continue: "
if /i not "%CONFIRM%"=="YES" (
    echo.
    echo Cancelled — nothing was removed.
    pause
    exit /b 0
)

taskkill /f /im IcarusStarlink.App.exe >nul 2>&1

rem Regenerable/transient folders — always removed regardless of the data choice above.
for %%D in (Logs Data Staged_Build Staged_UE4SS runtimes) do (
    if exist "%%D" rd /s /q "%%D"
)

if /i not "%KEEPDATA%"=="Y" (
    for %%D in (Extracted_Mods Library_Meta Profiles Cache Pending_Downloads Backups WebView2) do (
        if exist "%%D" rd /s /q "%%D"
    )
    if exist settings.json del /q settings.json
)

rem The app's own program files — DLLs/exe/pdb/xml are always removed. Never touches Uninstall.bat
rem itself (this script) or, when KEEPDATA=Y, the user-data folders/settings.json handled above.
for %%F in (*.dll *.exe *.pdb *.xml) do (
    if exist "%%F" del /q "%%F"
)
for %%F in (IcarusStarlink.App.deps.json IcarusStarlink.App.runtimeconfig.json) do (
    if exist "%%F" del /q "%%F"
)

echo.
if /i "%KEEPDATA%"=="Y" (
    echo Done. IcarusStarlink itself is removed. Your data is still here if you reinstall later.
) else (
    echo Done. IcarusStarlink and all its data have been removed from this folder.
)
echo This script and this folder are left behind — delete them yourself once you're done.
pause
